#在测试开发环境中将采用这个配置文件
server:
  #  配置https证书
  ssl:
    key-store: sang.p12
    key-alias: tomcathttps
    key-password: wbw901267

#  测试属性注入
book:
  name: springboot从入门到精通
  author: wubowen
  list:
    - configure
    - starter
    - controllser

#解决返回JSON中文乱码的问题
#此处注释掉是因为发现一些通用的配置仍然可以放在application.yml
#spring:
#  http:
#    encoding:
#      force-response: true

#redis相关配置
redis:
  host: localhost
  port: 6379
  jedis:
    pool:
      max-active: 8 #连接池最大连接数
      max-idle: 8 #连接池最大空闲连接数
      max-wait: -1ms #连接池最大阻塞等待时间，默认-1，表示没有限制
      min-idle: 0 #连接池最小空闲连接数
