#server:
#  #  配置https证书
#  ssl:
#    key-store: sang.p12
#    key-alias: tomcathttps
#    key-password: wbw901267
#
##  测试属性注入
#book:
#  name: springboot从入门到精通
#  author: wubowen
#  list:
#    - configure
#    - starter
#    - controllser

#通过这个配置的改动，我们将决定采用正式还是开发环境的配置文件
spring:
  profiles:
    active: prod